/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'index',
    {
      type: 'category',
      label: 'Contracts',
      link: {
        type: 'generated-index',
      },
      items: [{ type: 'autogenerated', dirName: 'contracts' }],
    },
  ],
};

module.exports = sidebars;